import Head from 'next/head'
import React, { useState, useEffect } from 'react';

export default function PageHead() {


  return (
    <>
      <Head>
        <title>HOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon/favicon.ico" />
      </Head>    
    </>
  )
}
