import Head from 'next/head'
import React, { useState, useEffect } from 'react';
import Hero from '../components/Hero'
import Nav from '../components/Nav'
import TextCtaSection from '../components/TextCtaSection'
import MasonGridSection from '../components/MasonGridSection'
import TextCarouselSection from '../components/TextCarouselSection'
import TextInfoSection from '../components/TextInfoSection'
import VideoSection from '../components/VideoSection'
import Footer from '../components/Footer'
import TextBlock from '../components/TextBlock'
import NewsletterBlock from '../components/NewsletterBlock'
import PodcastSection from '../components/PodcastSection'
import { onSnapshot, query } from 'firebase/firestore';
import { homepageRef } from '../firebaseConfig';

export default function Home() {
  // const [sectionData, setSectionData] = useState([]);

    // Fetch data from JSON
    // useEffect(() => {
    //     async function getData() {
    //         const response = await fetch("/data/homePageData.json");
    //         const data = await response.json();
    //         setSectionData(data);             
    //     }       
    //     getData();        
    // }, []);

    // useEffect(() => {
    //   const q = query(homepageRef);
    //   const unsubscribe = onSnapshot(q, (data) => {
    //     const homepageData = data.docs.map((doc) => {
    //       return { ...doc.data(), id: doc.id };
    //     });
    //     setSectionData(homepageData);
    //   });
    //   return () => unsubscribe();
    // }, []);

  return (
    <>

      <Head>
        <title>HOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page">
      {/* {sectionData.map((data) => (    
        <Hero key={sectionData.id}  data={data}/>

        ))} */}
        <Hero/>
        <TextBlock/>
        {/* <TextCtaSection/> */}
        <TextCarouselSection/>
        {/* <MasonGridSection/>     */}
        <TextInfoSection/>    
        <VideoSection/>
        <PodcastSection/>
        <NewsletterBlock/>
      </main>

    </>
  )
}
