import Head from 'next/head'
import Hero from '../components/Hero'
import Nav from '../components/Nav'
import TextCtaSection from '../components/TextCtaSection'
import MasonGridSection from '../components/MasonGridSection'
import TextCarouselSection from '../components/TextCarouselSection'
import TextInfoSection from '../components/TextInfoSection'

export default function Home() {
  return (
    <>
    <Nav/>
    <div>
      <Head>
        <title>HOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page">
        <Hero/>
        <TextCtaSection/>
        <TextCarouselSection/>
        <MasonGridSection/>    
        <TextInfoSection/>    
      </main>
 
    </div>
    </>
  )
}
